"""Add missing contraints to alembic
 * Unique constraint for fulfilment.code
 * Unique constraint for person_social_network_map.person_id and person_social_network_map.social_network_id

Revision ID: 436760a3036b
Revises: 624cf57a935
Create Date: 2015-05-02 04:29:39.013291

"""

# revision identifiers, used by Alembic.
revision = '436760a3036b'
down_revision = '624cf57a935'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('fulfilment_code_key', 'fulfilment', ['code'])
    op.create_unique_constraint('person_social_network_map_person_id_social_network_id_key', 'person_social_network_map', ['person_id', 'social_network_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('person_social_network_map_person_id_social_network_id_key', 'person_social_network_map', type_='unique')
    op.drop_constraint('fulfilment_code_key', 'fulfilment', type_='unique')
    ### end Alembic commands ###
