"""empty message

Revision ID: 209af87cb54
Revises: 2742a682f066
Create Date: 2012-08-29 22:35:00.597924

"""

# revision identifiers, used by Alembic.
revision = '209af87cb54'
down_revision = '2742a682f066'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT INTO proposal_status (name) VALUES ('Offered Travel'), ('Offered Accommodation'), ('Offered Travel Accommodation')")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM proposal_status WHERE name IN ('Offered Travel', 'Offered Accommodation', 'Offered Travel Accommodation')")
    ### end Alembic commands ###
