"""empty message

Revision ID: 30c8c19bec13
Revises: 4cecbeb21fbf
Create Date: 2012-09-06 12:47:22.027890

"""

# revision identifiers, used by Alembic.
revision = '30c8c19bec13'
down_revision = '4cecbeb21fbf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funding_type', sa.Column('notify_email', sa.String(), nullable=True))
    op.add_column('proposal_type', sa.Column('notify_email', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal_type', 'notify_email')
    op.drop_column('funding_type', 'notify_email')
    ### end Alembic commands ###
