"""
 * Rename Pending and Rejected Status' in ProposalStatus

Revision ID: 34a443e30750
Revises: 50a794ece403
Create Date: 2012-08-27 22:12:12.262280

"""

# revision identifiers, used by Alembic.
revision = '34a443e30750'
down_revision = '50a794ece403'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE proposal_status SET name='Pending Review' WHERE name='Pending'")
    op.execute("UPDATE proposal_status SET name='Declined' WHERE name='Rejected'")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE proposal_status SET name='Pending' WHERE name='Pending Review'")
    op.execute("UPDATE proposal_status SET name='Rejected' WHERE name='Declined'")
    ### end Alembic commands ###
