"""
 * Add parent_id to ceiling

Revision ID: 3b1b405d632e
Revises: 1e6ca7fcff4a
Create Date: 2012-09-24 01:37:29.895286

"""

# revision identifiers, used by Alembic.
revision = '3b1b405d632e'
down_revision = '1e6ca7fcff4a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ceiling', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ceiling', 'ceiling', ['parent_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ceiling', 'parent_id')
    ### end Alembic commands ###
