"""
Add badge_text column to product

Revision ID: 50062c1a43cb
Revises: 108bc71e0757
Create Date: 2013-01-27 02:18:07.654637

"""

# revision identifiers, used by Alembic.
revision = '50062c1a43cb'
down_revision = '108bc71e0757'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('badge_text', sa.Text()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'badge_text')
    ### end Alembic commands ###
