"""
 * Partial reversion of 29790706ec34
 * Allow NULL for url and abstract_video_url on Proposal

Revision ID: 50a794ece403
Revises: 29790706ec34
Create Date: 2012-08-26 23:47:43.102696

"""

# revision identifiers, used by Alembic.
revision = '50a794ece403'
down_revision = '29790706ec34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proposal', u'url', 
               existing_type=sa.TEXT(), 
               nullable=True)
    op.alter_column('proposal', u'abstract_video_url', 
               existing_type=sa.TEXT(), 
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proposal', u'abstract_video_url', 
               existing_type=sa.TEXT(), 
               nullable=False)
    op.alter_column('proposal', u'url', 
               existing_type=sa.TEXT(), 
               nullable=False)
    ### end Alembic commands ###
