"""Add a field for user salts

Revision ID: 590a0265a5f
Revises: 41a80a9e472
Create Date: 2015-05-03 10:36:23.196312

"""

# revision identifiers, used by Alembic.
revision = '590a0265a5f'
down_revision = '41a80a9e472'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('password_salt', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'password_salt')
    ### end Alembic commands ###
