import sqlalchemy.mods.threadlocal
from sqlalchemy import *

registration = Table('registration',
                     Column('id', Integer, primary_key=True),

                     Column('account_id', Integer, ForeignKey('account.id')),

                     Column('address1', String),
                     Column('address2', String),
                     Column('city', String),
                     Column('state', String),
                     Column('country', String),
                     Column('postcode', String),
                     Column('company', String),
                     Column('shell', String),
                     Column('shelltext', String),
                     Column('editor', String),
                     Column('editortext', String),
                     Column('distro', String),
                     Column('distrotext', String),
                     Column('type', String),
                     Column('discount_code', String),
                     Column('teesize', String),
                     Column('dinner', Integer),
                     Column('diet', String),
                     Column('special', String),
                     Column('opendaydrag', Integer),
                     Column('partner_email', String),
                     Column('kids_0_3', Integer),
                     Column('kids_4_6', Integer),
                     Column('kids_7_9', Integer),
                     Column('kids_10', Integer),
                     Column('accommodation', String),
                     Column('checkin', Integer),
                     Column('checkout', Integer),
                     Column('lasignup', Boolean),
                     Column('announcesignup', Boolean),
                     Column('delegatesignup', Boolean),
                     
                     )
