<div class="footer">
#<a href="http://anchor.com.au">premium australian webhosting by anchor</a>
#<br/>
#website powered by <a href="http://pylonshq.com">pylons</a>, deployed by <a href="http://pythonpaste.org">paste</a>, mapped by <a href="http://routes.groovie.org">routes</a>, and generated by <a href="http://www.myghty.org">myghty</a>
powered by zookeepr
</div>
</body>
</html>
