from zookeepr.tests.model import *

class TestPaymentReceivedTable(TableTest):
    table = model.billing.tables.payment_received
    samples = [dict(invoice_id=1000,
                    auth_num=5260,
                    amount=69000,
                    refund_key='KJdW+tSk95x+d54+gHB0',
                    merchant_id='Testlinuxlca',
                    status='Accepted',
                    settlement=1110,
                    error_string='a',
                    card_name='b',
                    requested_page='ReceiptPage',
                    card_type='MASTERCARD',
                    mac='0cf459a485261747bb565ec47ec434ee6fdba0fe',
                    card_number='51000...0008',
                    payment_id=200,
                    trans_id='SimProxy 54021549',
                    original_amount=69000,
                    surcharge=0),
               dict(invoice_id=1001,
                    auth_num=5261,
                    amount=69001,
                    refund_key='KJdW+tSk95x+d54+gHB1',
                    merchant_id='Testlinuxlca1',
                    status='Denied',
                    settlement=1111,
                    error_string='x',
                    card_name='y',
                    requested_page='ReceiptPage1',
                    card_type='VISA',
                    mac='0cf459a485261747bb565ec47ec434ee6fdbasdf',
                    card_number='51000...0009',
                    payment_id=201,
                    trans_id='SimProxy 54021550',
                    original_amount=69001,
                    surcharge=1),
               ]
